import { contextBuilder } from './contextBuilder.js';
import { chatStore } from './chatStore.js';
import { memoryStore } from './memoryStore.js';
import { findProjectById } from './models/Project.js';

const DEFAULT_HANDOFF_LIMIT = 8;
const DEFAULT_MEMORY_LIMIT = 12;

function truncate(value, maxLength = 500) {
  const text = String(value || '').replace(/\s+/g, ' ').trim();
  if (text.length <= maxLength) return text;
  return `${text.slice(0, maxLength - 3).trim()}...`;
}

function formatDate(value) {
  if (!value) return null;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  return date.toISOString();
}

function getBuildSystem(project) {
  if (!project?.folderPath) return null;
  try {
    return contextBuilder.detectBuildSystem(project.folderPath);
  } catch {
    return null;
  }
}

function summarizeSession(session) {
  const checkpoint = session?.contextCheckpoint || null;
  const summary = checkpoint?.summary || session?.lastContext || '';
  return {
    id: session.id,
    name: session.name || 'Untitled session',
    status: session.status || 'open',
    tool: session.tool || null,
    mode: session.mode || null,
    branch: session.branch || null,
    repoPath: session.repoPath || null,
    messageCount: session.messageCount || 0,
    updatedAt: formatDate(checkpoint?.updatedAt || session.lastContextAt || session.updatedAt || session.createdAt),
    starter: truncate(session.starter || '', 260),
    summary: truncate(summary, 700),
    source: checkpoint?.source || (session?.lastContext ? 'session-summary' : 'metadata'),
  };
}

function countBy(items, field) {
  const counts = {};
  for (const item of items) {
    const key = item?.[field] || 'unknown';
    counts[key] = (counts[key] || 0) + 1;
  }
  return counts;
}

function buildStatus({ project, memories, handoffs, sessions }) {
  const hasDescription = Boolean(project?.description?.trim());
  const hasRules = Array.isArray(project?.rules) && project.rules.length > 0;
  const hasMemories = memories.length > 0;
  const hasHandoffs = handoffs.some(handoff => handoff.summary);
  const hasSessions = sessions.length > 1;

  if (hasDescription && hasRules && (hasMemories || hasHandoffs)) {
    return {
      level: 'ready',
      label: 'Ready',
      reason: 'Project description/rules plus learned memory or session handoffs are available.',
    };
  }
  if (hasDescription || hasRules || hasMemories || hasHandoffs || hasSessions) {
    return {
      level: 'partial',
      label: 'Partial',
      reason: 'Context exists but is still missing durable project facts or recent handoffs.',
    };
  }
  return {
    level: 'building',
    label: 'Building',
    reason: 'No durable project context has been collected yet.',
  };
}

export function buildContextPackFromOverview(overview, { goal = '', sessionId = null } = {}) {
  const project = overview.project || {};
  const build = overview.buildSystem || null;
  const targetHandoff = sessionId
    ? overview.handoffs.find(handoff => handoff.id === sessionId)
    : null;
  const handoffs = targetHandoff ? [targetHandoff] : overview.handoffs.slice(0, DEFAULT_HANDOFF_LIMIT);
  const memories = overview.memories.slice(0, DEFAULT_MEMORY_LIMIT);
  const lines = [];

  lines.push('[Project Context Pack - generated by StartUpp AI IDE]');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push(`Project: ${project.name || 'Unknown project'}`);
  if (project.description) lines.push(`Description: ${truncate(project.description, 500)}`);
  lines.push(`Stack: ${project.stack || 'generic'}`);
  if (project.containerName) lines.push(`Container: ${project.containerName}`);
  if (project.folderPath) lines.push(`Local path: ${project.folderPath}`);
  if (Array.isArray(project.repos) && project.repos.length > 0) {
    lines.push(`Repos: ${project.repos.map(repo => repo.folder || repo.url).filter(Boolean).join(', ')}`);
  }
  if (goal) lines.push(`Current user goal: ${truncate(goal, 700)}`);

  if (build) {
    const scripts = Object.keys(build.scripts || {}).slice(0, 8);
    lines.push('');
    lines.push('Build and tooling:');
    lines.push(`- Language: ${build.language || 'unknown'}`);
    if (build.framework) lines.push(`- Framework: ${build.framework}`);
    if (build.packageManager) lines.push(`- Package manager: ${build.packageManager}`);
    if (build.testRunner) lines.push(`- Test runner: ${build.testRunner}`);
    if (scripts.length) lines.push(`- Scripts: ${scripts.join(', ')}`);
  }

  if (project.rules?.length) {
    lines.push('');
    lines.push('Project rules:');
    project.rules.slice(0, 8).forEach((rule, index) => lines.push(`${index + 1}. ${truncate(rule, 300)}`));
  }

  if (memories.length) {
    lines.push('');
    lines.push('Durable project memory:');
    memories.forEach(memory => {
      lines.push(`- [${memory.type}/${memory.category}] ${truncate(memory.content, 280)}`);
    });
  }

  if (handoffs.length) {
    lines.push('');
    lines.push('Recent session handoffs:');
    handoffs.forEach(handoff => {
      const details = [handoff.tool, handoff.mode, handoff.branch ? `branch=${handoff.branch}` : null]
        .filter(Boolean)
        .join(', ');
      lines.push(`- ${handoff.name}${details ? ` (${details})` : ''}: ${handoff.summary || handoff.starter || 'No summary captured yet.'}`);
    });
  }

  lines.push('');
  lines.push('Instructions for the next AI coding session:');
  lines.push('- Treat this pack as hidden handoff context. Do not repeat it back unless asked.');
  lines.push('- Verify repository state before assuming prior summaries are complete.');
  lines.push('- Continue from the latest relevant handoff and preserve project rules/preferences.');

  return lines.join('\n');
}

export function getProjectContextOverview(projectId, options = {}) {
  const project = findProjectById(projectId);
  if (!project) {
    const error = new Error('Project not found');
    error.statusCode = 404;
    throw error;
  }

  const memoryLimit = Math.max(1, Math.min(parseInt(options.memoryLimit, 10) || 50, 100));
  const handoffLimit = Math.max(1, Math.min(parseInt(options.handoffLimit, 10) || 20, 100));
  const buildSystem = getBuildSystem(project);
  const sessions = chatStore.getSessions(projectId, { includeArchived: true });
  const mainSession = sessions.find(session => session?.isMainThread) || null;
  const childSessions = sessions.filter(session => !session?.isMainThread);
  const memories = memoryStore.getAll(projectId).slice(0, memoryLimit);
  const handoffs = childSessions
    .map(summarizeSession)
    .sort((a, b) => new Date(b.updatedAt || 0).getTime() - new Date(a.updatedAt || 0).getTime())
    .slice(0, handoffLimit);

  const overview = {
    project: {
      id: project.id,
      name: project.name,
      description: project.description || '',
      stack: project.stack || 'generic',
      containerName: project.containerName || null,
      folderPath: project.folderPath || null,
      repos: Array.isArray(project.repos) ? project.repos : [],
      rules: Array.isArray(project.rules) ? project.rules : [],
      updatedAt: project.updatedAt || null,
    },
    buildSystem,
    memories,
    memoryStats: {
      total: memories.length,
      byType: countBy(memories, 'type'),
      byCategory: countBy(memories, 'category'),
    },
    sessions: {
      total: sessions.length,
      childCount: childSessions.length,
      main: mainSession ? summarizeSession(mainSession) : null,
    },
    handoffs,
    generatedAt: new Date().toISOString(),
  };
  overview.status = buildStatus({ project, memories, handoffs, sessions });
  overview.contextPack = buildContextPackFromOverview(overview, options);
  return overview;
}

export function buildPromptContextForLLM(projectId, { query = '', maxChars = 2800 } = {}) {
  const overview = getProjectContextOverview(projectId, {
    goal: query,
    memoryLimit: DEFAULT_MEMORY_LIMIT,
    handoffLimit: DEFAULT_HANDOFF_LIMIT,
  });
  const context = buildContextPackFromOverview(overview, { goal: query });
  if (context.length <= maxChars) return context;
  return `${context.slice(0, maxChars - 80).trim()}\n\n[Project context truncated to fit prompt budget.]`;
}

export default {
  getProjectContextOverview,
  buildContextPackFromOverview,
  buildPromptContextForLLM,
};
